#!/bin/bash
VERSION=0.0.2

echo "Checking for existing podman image..."
if ! ( podman image exists "reading-notes-notebook:${VERSION}" ); then
    echo "Building podman image..."
    podman build -t reading-notes-notebook:${VERSION} .
fi

LOGFILE="$(mktemp)"

function cleanup() {
    echo "cleaning up..."
    rm -f $LOGFILE
    kill $PODMAN_PID || true
}
trap cleanup EXIT

echo "logging to $LOGFILE"

# Find a free port (from https://gist.github.com/lusentis/8453523 )
read LOWERPORT UPPERPORT < /proc/sys/net/ipv4/ip_local_port_range
while :; do
    PORT="`shuf -i $LOWERPORT-$UPPERPORT -n 1`"
    ss -lpn | grep -q ":$PORT " || break
done

podman run --rm -p 127.0.0.1:$PORT:8888 \
    -u $(id -u):$(id -g) --userns=keep-id \
    -e JUPYTER_ENABLE_LAB=yes \
    -v "${PWD}":/home/jovyan \
    reading-notes-notebook:${VERSION} \
    > $LOGFILE 2>&1 &
PODMAN_PID=$!

printf "launching server"
while ! (grep -q http://127.0.0.1:8888 $LOGFILE \
        || ! kill -s 0 $PODMAN_PID); do
    printf .
    sleep 1
done
printf "\n"

# if the container crashed, print an error message
if (! kill -s 0 $PODMAN_PID); then
    echo "Podman container exited prematurely:"
    cat $LOGFILE
fi

URL=$(cat $LOGFILE \
    | grep http://127.0.0.1:8888 \
    | head -1 \
    | sed "s-.*http://127.0.0.1:8888-http://127.0.0.1:$PORT-g" \
)

echo "Launching firefox to connect to $URL"
firefox $URL

echo "press return to exit server..."
read
